"""Inference loop capturing MLP intermediate neuron activations and per-head attention outputs."""

import re
from typing import Any

import torch
import torch.nn as nn
import torch.nn.functional as F  # noqa: N812
from tqdm.auto import tqdm
from transformers import PreTrainedTokenizerFast

from model import LargeLanguageModel
from model.hooks import (
    AttentionHeadAblationHook,
    AttentionHeadExtractionStore,
    MlpNeuronAblationHook,
    MlpNeuronExtractionStore,
    MultiLayerActivationStore,
)
from utils.dataset import PromptDataset


def _map_char_to_token_position(
    tokenizer: PreTrainedTokenizerFast, token_ids: torch.Tensor, target_char_position: int
) -> int | None:
    """Map a character position to token position using incremental decoding.

    Fallback method when offset_mapping is not available.

    Args:
        tokenizer: The tokenizer used to decode tokens.
        token_ids: The token IDs that were decoded.
        target_char_position: The character position in the decoded text.

    Returns:
        The token index that contains or starts at the target character position,
        or None if mapping fails.
    """
    for token_idx in range(len(token_ids)):
        text_so_far = tokenizer.decode(token_ids[: token_idx + 1], skip_special_tokens=True)
        if len(text_so_far) > target_char_position:
            return token_idx
    return None


def _extract_answer_token_tensors(  # noqa: C901
    llm: LargeLanguageModel,
    prompt_length: int,
    output_ids: torch.Tensor,
    activations: dict[int, list[torch.Tensor]],
    logits: torch.Tensor,
    attentions: dict[int, list[torch.Tensor]],
) -> (
    tuple[dict[int, None], None, None, dict[int, None], None, None, None]
    | tuple[dict[Any, Any], torch.Tensor, torch.Tensor, dict[Any, Any], int, torch.Tensor, Any]
):
    """Extract token probabilities, activations, and attention for the answer token.

    For use with PROMPT_TEMPLATE_SMALL_LM, where the prompt ends with '=' and the
    model generates the numerical answer directly (e.g. '42'), with no 'Answer: ' prefix.

    Passing empty dicts ({}) for activations and attentions is valid: the function
    will return empty dicts for answer_activations and answer_attention, while still
    correctly extracting the answer token string from output_ids and logits.

    Args:
        llm: The large language model.
        prompt_length: The length of the prompt in tokens.
        output_ids: The output token IDs generated by the model.
        activations: Layer activations dict (may be empty).
        logits: The logits of the generated tokens, shape [seq_len_generated, vocab_size].
        attentions: Attention weights dict (may be empty).

    Returns:
        answer_activations: Activations at answer token per layer (empty if activations={}).
        answer_probs: Softmax probabilities for answer tokens.
        answer_logits: Logits for answer tokens.
        answer_attention: Attention weights at answer token per layer (empty if attentions={}).
        answer_position_in_output: Absolute position of the answer token in full output.
        answer_token_ids: Token IDs of the answer.
        answer_token: Decoded string of the answer.
    """

    def _none_tuple(activations: dict, attentions: dict) -> tuple:
        return (
            {layer_idx: None for layer_idx in activations.keys()},
            None,
            None,
            {layer_idx: None for layer_idx in attentions.keys()},
            None,
            None,
            None,
        )

    generated_ids = output_ids[prompt_length:]
    if len(generated_ids) == 0:
        return _none_tuple(activations, attentions)
    generated_text = llm.tokenizer.decode(generated_ids, skip_special_tokens=True)

    # Prompt ends with "="; model generates the answer number immediately.
    # Handles both normal format (e.g. "-46") and reverse-trained format (e.g. "64-").
    pattern = r"^\s*([+-]?\d+[+-]?)"
    match = re.search(pattern, generated_text)
    if not match:
        return _none_tuple(activations, attentions)

    answer_text = match.group(1)
    answer_start_char = match.start(1)
    answer_end_char = match.end(1)

    answer_start_token = _map_char_to_token_position(llm.tokenizer, generated_ids, answer_start_char)
    answer_end_token = _map_char_to_token_position(llm.tokenizer, generated_ids, answer_end_char - 1)

    if answer_start_token is None or answer_end_token is None:
        return _none_tuple(activations, attentions)

    answer_position_in_generated = answer_end_token

    if not (0 <= answer_start_token < logits.shape[0] and 0 <= answer_end_token < logits.shape[0]):
        return _none_tuple(activations, attentions)

    answer_logits = logits[answer_start_token : answer_end_token + 1]
    answer_probs = F.softmax(answer_logits, dim=-1)
    answer_token_ids = generated_ids[answer_start_token : answer_end_token + 1]
    answer_token = llm.tokenizer.decode(answer_token_ids, skip_special_tokens=True)

    if answer_token.strip() != answer_text:
        return _none_tuple(activations, attentions)

    answer_activations = {}
    for layer_idx in activations.keys():
        if answer_position_in_generated < len(activations[layer_idx]):
            act = activations[layer_idx][answer_position_in_generated]
            if act.dim() == 3:
                act = act[0, -1, :]
            elif act.dim() == 2:
                act = act[-1, :]
            answer_activations[layer_idx] = act
        else:
            answer_activations[layer_idx] = None

    answer_attention = {}
    for layer_idx in attentions.keys():
        if answer_position_in_generated < len(attentions[layer_idx]):
            full_attention_for_answer_token = attentions[layer_idx][answer_position_in_generated]
            answer_attention[layer_idx] = full_attention_for_answer_token[:, :prompt_length]
        else:
            answer_attention[layer_idx] = None

    answer_position_in_output = prompt_length + answer_position_in_generated

    return (
        answer_activations,
        answer_probs,
        answer_logits,
        answer_attention,
        answer_position_in_output,
        answer_token_ids,
        answer_token,
    )


def _find_token_positions(
    tokenizer: PreTrainedTokenizerFast,
    full_prompt: str,
    question: str,
    operator: str,
) -> tuple[int | None, int | None, int | None, int | None]:
    r"""Find token positions for operand A (last digit), operand B (last digit), operator, and '='.

    The full prompt ends with '\n{question}='. We locate the last occurrence of the
    question string, parse the two operands from it using the operator, then find the
    character positions of their last digits, the operator symbol, and the '=' sign,
    and map those to token indices via the tokenizer's offset mapping.

    Args:
        tokenizer: The model's tokenizer (must support return_offsets_mapping).
        full_prompt: The complete prompt string including the trailing '='.
        question: The question expression, e.g. '023+045' (no '=' suffix).
        operator: The operator symbol used to split operands, e.g. '+'.

    Returns:
        (pos_a, pos_b, pos_op, pos_eq): Token indices in the prompt for the last digit of
        operand A, the last digit of operand B, the operator symbol, and the '=' sign.
        Any may be None if the position cannot be determined.
    """
    try:
        question_start_char = full_prompt.rfind(question)
        if question_start_char == -1:
            return None, None, None, None

        op_idx = question.index(operator)
        operand_a_str = question[:op_idx]
        # Last char of operand A: question_start + end of operand A - 1
        char_pos_a = question_start_char + len(operand_a_str) - 1
        # First char of operator
        char_pos_op = question_start_char + op_idx
        # Last char of operand B: question_start + end of question - 1
        char_pos_b = question_start_char + len(question) - 1
        # '=' is the last character of the full prompt
        char_pos_eq = len(full_prompt) - 1

        encoding = tokenizer(full_prompt, return_offsets_mapping=True, return_tensors="pt")
        offsets = encoding["offset_mapping"][0].tolist()  # [(start, end), ...]

        def _char_to_token(char_pos: int) -> int | None:
            for tok_idx, (start, end) in enumerate(offsets):
                if start <= char_pos < end:
                    return tok_idx
            return None

        return (
            _char_to_token(char_pos_a),
            _char_to_token(char_pos_b),
            _char_to_token(char_pos_op),
            _char_to_token(char_pos_eq),
        )

    except (ValueError, IndexError):
        return None, None, None, None


def _extract_all_activations(  # noqa: C901
    activations: dict[int, list[torch.Tensor]],
    mlp_store: MlpNeuronExtractionStore,
    head_store: AttentionHeadExtractionStore,
    layer_indices: list[int],
    pos_a: int | None,
    pos_b: int | None,
    pos_op: int | None,
    pos_eq: int | None,
    embedding_tensor: torch.Tensor | None = None,
) -> dict[str, dict[int, dict[str, torch.Tensor | None]]]:
    """Extract residual stream, MLP neuron, and attention head activations at prompt token positions.

    Uses the step-0 full-prompt pass for all three activation types:
      - Residual stream: activations[layer][0], shape [1, prompt_len, hidden_size]
      - MLP neurons: mlp_store.activations[layer][0], shape [1, prompt_len, intermediate_size]
      - Attention heads: head_store.activations[layer][0], shape [1, prompt_len, num_heads, head_dim]

    If embedding_tensor is provided, also populates layer_idx=-1 with the token embedding
    representation (before any transformer block), with mlp=None and heads=None.

    All sliced at the specified token positions to produce per-position, per-layer dicts.

    Args:
        activations: Residual stream activations from llm.extract_activations().
        mlp_store: MLP intermediate activation store (hooked for the forward pass).
        head_store: Attention head activation store (hooked for the forward pass).
        layer_indices: Layer indices to extract from.
        pos_a: Token index of the last digit of operand A.
        pos_b: Token index of the last digit of operand B.
        pos_op: Token index of the operator symbol.
        pos_eq: Token index of the '=' sign.
        embedding_tensor: Optional [prompt_len, hidden_size] tensor from the token embedding
            layer (embed_tokens output at step 0). If provided, stored at layer_idx=-1.

    Returns:
        dict with keys 'operand_a', 'operand_b', 'operator', 'eq_sign'. Each maps
        layer_idx -> {"residual": Tensor | None, "mlp": Tensor | None, "heads": Tensor | None}.
        layer_idx=-1 holds the pre-transformer token embedding (residual only, mlp/heads=None).
    """
    positions = {
        "operand_a": pos_a,
        "operand_b": pos_b,
        "operator": pos_op,
        "eq_sign": pos_eq,
    }
    geometry: dict[str, dict] = {name: {} for name in positions}

    # Populate layer_idx=-1 with the token embedding (pre-transformer representation).
    if embedding_tensor is not None:
        for name, pos in positions.items():
            if pos is None or pos < 0 or pos >= embedding_tensor.shape[0]:
                geometry[name][-1] = {"residual": None, "mlp": None, "heads": None}
            else:
                geometry[name][-1] = {
                    "residual": embedding_tensor[pos].detach().clone().cpu(),
                    "mlp": None,
                    "heads": None,
                }

    for layer_idx in layer_indices:
        # Step-0 residual stream tensor: [1, prompt_len, hidden_size] → [prompt_len, hidden_size]
        resid_steps = activations.get(layer_idx, [])
        step0_resid = None
        if resid_steps:
            t = resid_steps[0]
            step0_resid = t[0] if t.dim() == 3 else (t.unsqueeze(0) if t.dim() == 1 else t)

        # Step-0 MLP neuron tensor: [1, prompt_len, intermediate_size] → [prompt_len, intermediate_size]
        mlp_steps = mlp_store.activations.get(layer_idx, [])
        step0_mlp = None
        if mlp_steps:
            t = mlp_steps[0]
            step0_mlp = t[0] if t.dim() == 3 else t

        # Step-0 attention head tensor: [1, prompt_len, num_heads, head_dim] → [prompt_len, num_heads, head_dim]
        head_steps = head_store.activations.get(layer_idx, [])
        step0_heads = None
        if head_steps:
            t = head_steps[0]
            step0_heads = t[0] if t.dim() == 4 else t

        for name, pos in positions.items():
            if pos is None:
                geometry[name][layer_idx] = {"residual": None, "mlp": None, "heads": None}
                continue

            def _slice(tensor: torch.Tensor | None, pos: int = pos) -> torch.Tensor | None:
                if tensor is None or pos < 0 or pos >= tensor.shape[0]:
                    return None
                return tensor[pos].detach().clone().cpu()

            geometry[name][layer_idx] = {
                "residual": _slice(step0_resid),
                "mlp": _slice(step0_mlp),
                "heads": _slice(step0_heads),  # [num_heads, head_dim]
            }

    return geometry


def _extract_neuron_tensors_at_position(
    mlp_store: MlpNeuronExtractionStore,
    head_store: AttentionHeadExtractionStore,
    answer_position_in_generated: int,
    layer_indices: list[int],
) -> tuple[dict[int, torch.Tensor | None], dict[int, torch.Tensor | None]]:
    """Extract MLP neuron and attention head activations at the answer token generation step.

    Args:
        mlp_store: Store containing MLP intermediate activations per layer per generation step.
        head_store: Store containing per-head attention outputs per layer per generation step.
        answer_position_in_generated: Index of the answer token in the generated sequence (0-indexed).
        layer_indices: Layer indices to extract from.

    Returns:
        mlp_neurons: dict mapping layer_idx to Tensor[intermediate_size], or None if unavailable.
        attn_heads: dict mapping layer_idx to Tensor[num_heads, head_dim], or None if unavailable.
    """
    mlp_neurons: dict[int, torch.Tensor | None] = {}
    attn_heads: dict[int, torch.Tensor | None] = {}

    for layer_idx in layer_indices:
        # MLP intermediate neurons
        mlp_acts = mlp_store.activations.get(layer_idx, [])
        if answer_position_in_generated < len(mlp_acts):
            act = mlp_acts[answer_position_in_generated]  # [B, seq_len, intermediate_size]
            if act.dim() == 3:
                act = act[0, -1, :]  # [intermediate_size]
            elif act.dim() == 2:
                act = act[-1, :]
            mlp_neurons[layer_idx] = act
        else:
            mlp_neurons[layer_idx] = None

        # Per-head attention outputs
        head_acts = head_store.activations.get(layer_idx, [])
        if answer_position_in_generated < len(head_acts):
            act = head_acts[answer_position_in_generated]  # [B, seq_len, num_heads, head_dim]
            if act.dim() == 4:
                act = act[0, -1, :, :]  # [num_heads, head_dim]
            elif act.dim() == 3:
                act = act[-1, :, :]
            attn_heads[layer_idx] = act
        else:
            attn_heads[layer_idx] = None

    return mlp_neurons, attn_heads


def _register_ablation_hooks(
    llm: LargeLanguageModel,
    down_proj_layers: dict[int, nn.Module],
    o_proj_layers: dict[int, nn.Module],
    mlp_ablation: dict[int, list[int]] | None,
    head_ablation: dict[int, list[int]] | None,
) -> list:
    """Register MLP and attention-head ablation hooks and return the hook objects.

    Ablation hooks must be registered before extraction stores so that PyTorch
    fires them first; the extraction store then captures the already-zeroed
    activations, which is what actually flowed through the model.

    Args:
        llm: The large language model (used for num_attention_heads / head_dim).
        down_proj_layers: Dict mapping layer_idx to mlp.down_proj modules.
        o_proj_layers: Dict mapping layer_idx to self_attn.o_proj modules.
        mlp_ablation: Optional dict mapping layer_idx to MLP neuron indices to zero.
        head_ablation: Optional dict mapping layer_idx to attention head indices to zero.

    Returns:
        List of registered hook objects; call .remove() on each to clean up.
    """
    hooks: list = []
    if mlp_ablation:
        for layer_idx, neuron_indices in mlp_ablation.items():
            if layer_idx in down_proj_layers:
                hooks.append(MlpNeuronAblationHook(down_proj_layers[layer_idx], neuron_indices))
    if head_ablation:
        for layer_idx, head_indices in head_ablation.items():
            if layer_idx in o_proj_layers:
                hooks.append(
                    AttentionHeadAblationHook(
                        o_proj_layers[layer_idx], head_indices, llm.num_attention_heads, llm.head_dim
                    )
                )
    return hooks


def _run_single_prompt(  # noqa: C901
    llm: LargeLanguageModel,
    prompt: str,
    prompt_length: int,
    question: str,
    operator: str,
    layers: dict[int, nn.Module],
    down_proj_layers: dict[int, nn.Module],
    o_proj_layers: dict[int, nn.Module],
    max_new_tokens: int,
    mlp_ablation: dict[int, list[int]] | None = None,
    head_ablation: dict[int, list[int]] | None = None,
    capture_geometry: bool = True,
) -> dict[str, Any]:
    """Run a single prompt through the model, capturing neuron-level and geometry activations.

    Args:
        llm: The large language model.
        prompt: Full prompt string (few-shot examples + question + '=').
        prompt_length: Number of tokens in the prompt.
        question: The bare question expression, e.g. '023+045'.
        operator: Operator symbol used to split operands for geometry extraction.
        layers: Transformer layer modules for residual-stream extraction.
        down_proj_layers: Dict mapping layer_idx to mlp.down_proj modules.
        o_proj_layers: Dict mapping layer_idx to self_attn.o_proj modules.
        max_new_tokens: Maximum tokens to generate.
        mlp_ablation: Optional dict mapping layer_idx to MLP neuron indices to zero out.
        head_ablation: Optional dict mapping layer_idx to attention head indices to zero out.
        capture_geometry: If True, extract step-0 activations at operand/operator/'=' positions
            and store output_ids. Set to False during ablation sweeps to reduce stored data.

    Returns:
        Dict with keys: text, completion, output_ids (None when capture_geometry=False), and
        an answer sub-dict (position, token_id, token, mlp_neurons, attn_heads, residual, logits)
        plus a geometry sub-dict (empty when capture_geometry=False).
    """
    layer_indices = list(layers.keys())

    # Ablation hooks register FIRST; extraction stores register AFTER (when used).
    # PyTorch fires pre-hooks in registration order, so ablation zeroes the
    # tensor before the extraction store captures it.
    _ablation_hooks = _register_ablation_hooks(llm, down_proj_layers, o_proj_layers, mlp_ablation, head_ablation)

    if capture_geometry:
        mlp_store = MlpNeuronExtractionStore(down_proj_layers)
        head_store = AttentionHeadExtractionStore(o_proj_layers, llm.num_attention_heads, llm.head_dim)
        emb_store = MultiLayerActivationStore({-1: llm.get_embedding_layer()})
    else:
        mlp_store = MlpNeuronExtractionStore({})
        head_store = AttentionHeadExtractionStore({}, llm.num_attention_heads, llm.head_dim)
        emb_store = None

    (
        activations,
        generated_text,
        completion,
        logits,
        attentions,
        output_ids,
    ) = llm.extract_activations(prompt, layers, max_new_tokens=max_new_tokens)

    for hook in _ablation_hooks:
        hook.remove()

    (
        _,
        _,
        answer_logits,
        _,
        answer_position_in_output,
        answer_token_ids,
        answer_token,
    ) = _extract_answer_token_tensors(
        llm,
        prompt_length,
        output_ids,
        activations,
        logits,
        attentions,
    )

    if capture_geometry and answer_position_in_output is not None:
        answer_pos_in_gen = answer_position_in_output - prompt_length
        mlp_neurons, attn_heads = _extract_neuron_tensors_at_position(
            mlp_store, head_store, answer_pos_in_gen, layer_indices
        )
        answer_residual: dict[int, torch.Tensor | None] = {}
        for layer_idx in layer_indices:
            acts = activations.get(layer_idx, [])
            if answer_pos_in_gen < len(acts):
                act = acts[answer_pos_in_gen]
                if act.dim() == 3:
                    act = act[0, -1, :]
                elif act.dim() == 2:
                    act = act[-1, :]
                answer_residual[layer_idx] = act.detach().clone().cpu()
            else:
                answer_residual[layer_idx] = None

        # Extract token embedding at the answer generation step (layer_idx=-1).
        # emb_store captures every forward call to embed_tokens; answer_pos_in_gen+1
        # because step 0 is the full prompt pass and steps 1..N are single-token passes.
        answer_embedding: torch.Tensor | None = None
        if emb_store is not None:
            emb_acts = emb_store.activations.get(-1, [])
            answer_emb_step = answer_pos_in_gen + 1  # step 0 = prompt, steps 1..N = generated tokens
            if answer_emb_step < len(emb_acts):
                t = emb_acts[answer_emb_step]
                # Single-token call: shape [1, 1, hidden] → [hidden]
                if t.dim() == 3:
                    answer_embedding = t[0, -1, :].detach().clone().cpu()
                elif t.dim() == 2:
                    answer_embedding = t[-1, :].detach().clone().cpu()

        pos_a, pos_b, pos_op, pos_eq = _find_token_positions(llm.tokenizer, prompt, question, operator)

        # Extract prompt-phase embedding tensor: step-0 output of embed_tokens [prompt_len, hidden].
        step0_embedding: torch.Tensor | None = None
        if emb_store is not None:
            emb_acts = emb_store.activations.get(-1, [])
            if emb_acts:
                t = emb_acts[0]
                step0_embedding = t[0] if t.dim() == 3 else t  # [prompt_len, hidden]

        geometry = _extract_all_activations(
            activations,
            mlp_store,
            head_store,
            layer_indices,
            pos_a,
            pos_b,
            pos_op,
            pos_eq,
            embedding_tensor=step0_embedding,
        )
    else:
        mlp_neurons = {i: None for i in layer_indices}
        attn_heads = {i: None for i in layer_indices}
        answer_residual = {i: None for i in layer_indices}
        answer_embedding = None
        geometry = {}

    mlp_store.remove_all_hooks()
    mlp_store.clear()
    head_store.remove_all_hooks()
    head_store.clear()
    if emb_store is not None:
        emb_store.remove_all_hooks()
        emb_store.clear()

    return {
        "text": generated_text,
        "completion": completion,
        "output_ids": output_ids if capture_geometry else None,
        "answer": {
            "position": answer_position_in_output,
            "token_id": answer_token_ids,
            "token": answer_token,
            "mlp_neurons": mlp_neurons,
            "attn_heads": attn_heads,
            "residual": answer_residual,
            "embedding": answer_embedding,
            "logits": answer_logits.cpu() if answer_logits is not None else None,
        },
        "geometry": geometry,
    }


def run(
    llm: LargeLanguageModel,
    dataset: PromptDataset,
    layers: dict[int, nn.Module],
    max_new_tokens: int,
    operator: str = "",
    mlp_ablation: dict[int, list[int]] | None = None,
    head_ablation: dict[int, list[int]] | None = None,
    capture_geometry: bool = True,
) -> list[dict[str, Any]]:
    """Run inference capturing MLP intermediate, per-head, and geometry activations.

    Args:
        llm: The large language model.
        dataset: Dataset of prompts to run.
        layers: Transformer layer modules (used for residual stream extraction via extract_activations).
        max_new_tokens: Max tokens to generate per prompt.
        operator: The arithmetic operator symbol (e.g. '+') used to split operands for
            geometry extraction. If empty, geometry positions will all be None.
        mlp_ablation: Optional dict mapping layer_idx to list of MLP neuron indices to zero out
            on every prompt. Applied to both original and overloaded runs.
        head_ablation: Optional dict mapping layer_idx to list of attention head indices to zero out
            on every prompt. Applied to both original and overloaded runs.
        capture_geometry: If True, extract step-0 activations at operand/operator/'=' positions.
            Set to False during ablation sweeps to avoid storing per-feature geometry data.

    Returns:
        List of result dicts, one per prompt. Each dict contains original and overloaded runs
        with mlp_neurons and attn_heads at the answer token, plus geometry activations at
        the operand and '=' positions.
    """
    down_proj_layers = llm.get_mlp_down_proj_layers(list(layers.keys()))
    o_proj_layers = llm.get_attn_o_proj_layers(list(layers.keys()))

    results: list[dict[str, Any]] = []
    prompt_template = llm.PROMPT_TEMPLATE_SMALL_LM

    for prompt_idx, prompt in enumerate(tqdm(dataset.prompts, desc="Running neuron inference")):
        prompt_original = prompt_template.format(
            "\n".join(prompt.examples_original),
            prompt.question,
        )
        prompt_original_length = len(llm.tokenizer(prompt_original, return_tensors="pt")["input_ids"][0])

        prompt_overloaded = prompt_template.format(
            "\n".join(prompt.examples_overloaded),
            prompt.question,
        )
        prompt_overloaded_length = len(llm.tokenizer(prompt_overloaded, return_tensors="pt")["input_ids"][0])

        original_run = _run_single_prompt(
            llm,
            prompt_original,
            prompt_original_length,
            prompt.question,
            operator,
            layers,
            down_proj_layers,
            o_proj_layers,
            max_new_tokens,
            mlp_ablation=mlp_ablation,
            head_ablation=head_ablation,
            capture_geometry=capture_geometry,
        )
        overloaded_run = _run_single_prompt(
            llm,
            prompt_overloaded,
            prompt_overloaded_length,
            prompt.question,
            operator,
            layers,
            down_proj_layers,
            o_proj_layers,
            max_new_tokens,
            mlp_ablation=mlp_ablation,
            head_ablation=head_ablation,
            capture_geometry=capture_geometry,
        )

        results.append(
            {
                "prompt_idx": prompt_idx,
                "prompt_original": prompt_original,
                "prompt_overloaded": prompt_overloaded,
                "prompt_original_length": prompt_original_length,
                "prompt_overloaded_length": prompt_overloaded_length,
                "answer_original": prompt.answer_original,
                "answer_overloaded": prompt.answer_overloaded,
                "original": original_run,
                "overloaded": overloaded_run,
            }
        )

    return results
